plugin:
    name: 'imbasynergy.imbachatwidget::lang.plugin.name'
    description: 'imbasynergy.imbachatwidget::lang.plugin.description'
    author: 'ImbaSynergy'
    icon: oc-icon-level-down
    homepage: 'http://octobercms.imbachat.com'
